export const DATATABLE_LABELS = {
    globalSearchPlaceholder: 'Genel ara...',
    filters: 'Filtreler',
    sort: 'Sırala',
    refresh: 'Yenile',
    exportExcel: 'Excel olarak indir',
    clearFilters: 'Filtreleri Temizle',
    clearAllFilters: 'Tümünü temizle',
    close: 'Kapat',
    activeFilters: 'Aktif Filtreler',
    noActiveFilters: 'Aktif filtre bulunmuyor.',
    showDetails: 'Detayı göster',
    hideDetails: 'Detayı gizle',
    empty: 'Henüz kayıt bulunmuyor.',
    emptyFiltered: 'Filtrelere uygun kayıt bulunamadı.',
    sortAscending: 'Artan',
    sortDescending: 'Azalan',
    clearSort: 'Sıralamayı kaldır',
    previous: 'Önceki',
    next: 'Sonraki',
    records: 'kayıt',
    rowsPerPage: 'Sayfa boyutu',
    selectColumns: 'Sütunları Seç',
    actions: 'İşlemler',
    matchMode: 'Eşleşme',
    operator: 'Operatör',
    operatorAnd: 'Ve',
    operatorOr: 'Veya',
    yes: 'Evet',
    no: 'Hayır',
    selectPlaceholder: 'Seçiniz',
    searchPlaceholder: 'Ara...',
    valuePlaceholder: 'Değer',
    moreActions: 'Diğer işlemler',
} as const;
